name: Deploy DEV

on:
  push:
    branches: [dev]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
      
      - name: Build and push the image
        env:
          PUBLIC_VAPID_SUBJECT: ${{ secrets.PUBLIC_VAPID_SUBJECT }}
          PUBLIC_VAPID_KEY: ${{ secrets.PUBLIC_VAPID_KEY }}
          PRIVATE_VAPID_KEY: ${{ secrets.PRIVATE_VAPID_KEY }}
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker build . --tag ghcr.io/${{ github.actor }}/cogni-test-dev:latest \
            --build-arg PUBLIC_VAPID_SUBJECT="$PUBLIC_VAPID_SUBJECT" \
            --build-arg PUBLIC_VAPID_KEY="$PUBLIC_VAPID_KEY" \
            --build-arg PRIVATE_VAPID_KEY="$PRIVATE_VAPID_KEY" \
            --build-arg MODE=DEV \
            --build-arg BUILD=node
          docker push ghcr.io/${{ github.actor }}/cogni-test-dev:latest
      
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/server_key
          chmod 600 ~/.ssh/server_key
      
      - name: Deploy using DOCKER_HOST
        env:
          DOCKER_HOST: ssh://${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}
          PUBLIC_VAPID_SUBJECT: ${{ secrets.PUBLIC_VAPID_SUBJECT }}
          PUBLIC_VAPID_KEY: ${{ secrets.PUBLIC_VAPID_KEY }}
          PRIVATE_VAPID_KEY: ${{ secrets.PRIVATE_VAPID_KEY }}
        run: |
          # Теперь все docker команды выполняются на удаленном сервере
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker compose --profile dev up -d --pull always --remove-orphans --force-recreate --wait --wait-timeout 30
          docker image prune -f